[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.121.1"
  HUGO_ENV = "production"
  HUGO_EXTENDED = "true"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200